### ISSUE TITLE
Собранный релиз cfe

### ISSUE THREAD

**Issue by khorevaa** [ValentinKozlov/1C_ConnectorMinio#1]
Хорошо бы....

**Comment by ValentinKozlov** [comment]
Я не понял комментария. Если есть какие-то проблемы со сбором расширения из файлов пишите.

**Comment by khorevaa** [comment]
Не хорошо бы при выпуске релиза класть собранный cfe. 
Вообще проблема со сборкой есть т.к. нет инструкции.  
К примеру:
1. Какую версию платформы использовать для сборки?
2. Надо ли делать сборку в базе с конфигурацией БУ? или достаточно бСП?

**Comment by ValentinKozlov** [comment]
Я не понял фразу "Не хорошо бы при выпуске релиза класть собранный cfe", но судя по тому что файла cfe нет, то речь идет о том что его нужно положить. Если это так, то так делать нельзя так как репозиторий это хранилище кода. Я поначалу так делал, но старшие товарищи меня ругали.
Требования есть внутри конфигурации:
Требования: Версия БСП 3.1.6.118 и выше (на других не тестировалось)
Перенес в readme.

**Comment by khorevaa** [comment]
Ну сделай просто по аналогии 
https://github.com/oscript-library/gitsync/releases/tag/3.4.1
 
В ассерты запихни собранную cfe и это сразу всем облегчит жизнь )

**Comment by ValentinKozlov** [comment]
Хорошо, спасибо. Я еще пока не разбирался как сделать, руки дойдут гляну и выложу.

**Comment by ValentinKozlov** [comment]
Добавил cfe
